### ISSUE TITLE
Quality control check

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/mcelhanonhuon#1]
Please check I've done everything properly!

**Comment by LinguList** [comment]
looks good, only adding an orthoprofile seems possible and easy, so useful.

**Comment by xrotwang** [comment]
Yes, looks good. I took a stab at adding an orthography profile here #2

**Comment by SimonGreenhill** [comment]
Looks great, thanks. 

I just realised that we should try to force the implementation of iter_raw_lexemes, and use that in `install` rather than `read_tsv` directly.
